language: python

python:
  - "2.7"

env:
  - TRAVIS_MODE=1
  - DJANGO_SETTINGS_MODULE=settings

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# Set Travis builds to use docker container
sudo: false

# Install dependencies
install:
    - "pip install -r requirements.txt"
    - "pip install -r test_requirements.txt"
    - "pip install coveralls"
    - "pip install pep8"
    - "pip install pylint"

# Run tests and quality checks
script:
    - coverage run ./manage.py test organizations
    - coverage report -m
    - pep8 --config=.pep8 organizations
    - pylint --rcfile=.pylintrc organizations --report=no

# Post results to Coveralls.io
after_success: coveralls

# Monitor changes to the master branch
branches:
    only:
      - master
