language: python

python:
  - "2.7"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# Set Travis builds to use docker container
sudo: false

install:
    - "pip install -r requirements.txt"
    - "pip install coveralls"

script:
    - DJANGO_SETTINGS_MODULE=settings coverage run ./manage.py test organizations
    - pep8 --config=.pep8 organizations
    - pylint --rcfile=.pylintrc organizations --reports=no

after_success: coveralls

